version: "3.3"

services:
 
      
  frontend:
    build:
      context: frontend
    volumes:
      - dist:/app/dist
    networks:
      - app-network

  backend:
    build:
      context: backend
    networks:
      - app-network

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    command: certonly --webroot -w /var/www/certbot --force-renewal --email devmarlen@mail.ru -d 24demo.ru --agree-tos

volumes:
  dist:

networks:
  app-network:
    driver: bridge