version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5432:80"
      #5432 это на моем компе 80 это порт в контейнере 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"