version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build: ./backend
    expose:
      - "3001"
    networks:
      - dev

networks:
  dev:
