version: "3.3"

services:
 
      
  frontend:
    build:
      context: frontend
    volumes:
      - dist:/app/dist
    networks:
      - app-network

  backend:
    build:
      context: backend
    networks:
      - app-network

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  dist:

networks:
  app-network:
    driver: bridge