version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - "3000"

  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "3001"
